INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('18-1-15','Nunc malesuada dictum Mauris',1);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('11-1-15','ultrices vehicula nostra senectus tristique dis vestibulum consequat imperdiet tellus pulvinar porta sociosqu cubilia elementum',2);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('29-11-14','nisl nisl scelerisque Donec sociosqu ut justo elit',3);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('17-12-14','Praesent hymenaeos vitae sociosqu primis conubia euismod congue dapibus Donec massa dignissim ornare mollis rutrum erat sagittis senectus',4);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('27-11-14','commodo lacinia suscipit facilisi sollicitudin Mauris conubia sem ante Integer ornare sollicitudin libero viverra posuere',5);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('6-1-15','semper',6);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('16-12-14','venenatis hendrerit malesuada posuere lacus auctor ornare tortor',7);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('2-11-14','fringilla facilisi Donec ullamcorper arcu magnis non mollis tristique orci eros Ut gravida porttitor orci turpis feugiat vehicula tristique',8);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('5-1-15','sem arcu congue blandit pulvinar nibh Vivamus Integer Nulla montes primis Nam ipsum dignissim vulputate morbi gravida',9);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('23-12-14','mauris Mauris parturient aliquam suscipit Phasellus',10);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('19-12-14','elit cursus est tortor ante Aenean egestas massa',11);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('10-11-14','condimentum placerat',12);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('8-11-14','ligula felis consequat blandit vel aliquam',13);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('29-12-14','ultricies at accumsan est a fames sapien tristique condimentum Curabitur consequat',14);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('18-11-14','taciti litora Pellentesque Curabitur orci dapibus Curabitur viverra',15);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('15-12-14','posuere inceptos ad sed aptent mattis ligula blandit tempus penatibus ultricies Quisque feugiat rutrum ullamcorper pharetra lorem dolor eget dolor',16);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('7-1-15','placerat aliquet augue accumsan imperdiet mauris Nulla convallis feugiat Integer',17);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('11-1-15','hendrerit senectus',18);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('8-11-14','Mauris lacus pretium Proin fermentum semper arcu fringilla tortor Donec pede facilisis natoque felis placerat viverra',19);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('29-12-14','tincidunt netus dolor montes facilisis purus ac nascetur ad ullamcorper',20);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('9-1-15','aptent malesuada magnis Curae augue amet mollis vitae arcu pretium natoque',21);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('25-12-14','Curabitur vestibulum mi tempor vehicula faucibus sociis',22);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('17-1-15','Duis justo adipiscing senectus elementum porta fames sociosqu',23);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('18-12-14','Praesent eu dis Proin elementum Maecenas justo magna purus amet magna turpis neque pede morbi interdum litora montes',24);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('27-12-14','dolor dui Vivamus conubia commodo convallis nonummy lobortis imperdiet sagittis Curae Curae quam ullamcorper Curae blandit',25);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('15-12-14','Aenean habitant massa dui vitae',26);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('30-11-14','dis mattis Fusce nunc mauris eget accumsan volutpat fames odio In',27);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('1-1-15','dignissim elit tempor dui cubilia rutrum nascetur pulvinar primis luctus auctor',28);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('24-11-14','Donec ligula Vivamus Nunc',29);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('9-12-14','ornare sed penatibus est enim sociis tempus vehicula senectus Curae egestas odio Lorem',30);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('12-1-15','Ut tempus accumsan parturient cubilia fermentum consectetuer quis Nulla orci vestibulum',31);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('27-12-14','lorem in augue Proin amet lacus nec dapibus montes ipsum',32);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('6-1-15','ultricies Aliquam dui habitant pharetra magna facilisis mus',33);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('18-11-14','sociis malesuada imperdiet malesuada felis Duis odio',34);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('17-12-14','eros',35);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('6-1-15','luctus Aenean',36);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('15-1-15','nostra purus mi habitant aliquet odio accumsan Vivamus',37);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('11-12-14','rutrum placerat malesuada nec dapibus Mauris congue leo tortor per cubilia',38);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('29-11-14','Morbi scelerisque Fusce posuere ut magna commodo est mollis Aliquam eleifend habitant dictum mattis aptent volutpat ipsum vulputate ullamcorper cubilia',39);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('18-12-14','habitant',40);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('20-12-14','Fusce tempus sit dignissim mauris dis arcu vulputate congue montes hendrerit augue viverra augue auctor scelerisque',41);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('20-12-14','taciti Nam Lorem nisl diam tortor inceptos porttitor elit Nullam neque sed eu taciti est feugiat',42);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('9-1-15','condimentum Integer porttitor magna viverra vel pellentesque eget elementum magna ultricies mi',43);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('29-11-14','pharetra litora felis eu elit tristique eros faucibus euismod suscipit morbi litora a non sem',44);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('19-1-15','urna risus aptent eros metus quam porttitor posuere in venenatis Vestibulum sociis tristique litora leo',45);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('5-11-14','consequat magnis felis aliquet quam ullamcorper nec varius mi eget fames Cras pellentesque',46);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('15-1-15','aliquam ultricies rhoncus commodo lorem ante fringilla blandit parturient vel gravida consequat ad enim quis consectetuer lectus aliquam',47);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('17-12-14','montes libero iaculis tempus',48);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('1-1-15','Curae',49);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('13-11-14','pretium erat consectetuer Donec magna sollicitudin sapien amet ligula tellus viverra a at taciti porttitor Lorem vehicula ante magnis',50);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('1-1-15','sodales nisi morbi conubia',51);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('1-11-14','Etiam nunc facilisis ligula leo Cum euismod est aliquam aliquet orci rhoncus',52);
INSERT INTO COMMANDE (`COMMANDE_DATE`,`COMMANDE_DESCRIPTION`,`UTILISATEUR_ID`) VALUES ('22-11-14','quam mauris nostra urna felis faucibus odio Sed imperdiet a nascetur mollis molestie sem natoque consectetuer facilisis eget eget egestas',53);
